using System;
using Xunit;
using Triptales.Application.Model;

namespace Triptales.Application.Tests
{
    public sealed class UserTests
    {
        [Fact]
        public void Constructor_WhenCalled_ShouldInitializeSecurityFields()
        {
            var sut = new User("tester", "tester@example.com", "S3cureP@ss!", "Tester");

            Assert.False(string.IsNullOrWhiteSpace(sut.Salt));
            Assert.False(string.IsNullOrWhiteSpace(sut.PasswordHash));
            Assert.NotEqual(sut.Salt, sut.PasswordHash);
        }

        [Theory]
        [InlineData("S3cureP@ss!", true)]
        [InlineData("WrongPassword", false)]
        public void CheckPassword_WithPasswordVerification_ReturnsExpectedResult(string passwordToCheck, bool expected)
        {
            var sut = new User("tester", "tester@example.com", "S3cureP@ss!", "Tester");

            var actual = sut.CheckPassword(passwordToCheck);

            Assert.Equal(expected, actual);
        }

        [Fact]
        public void SetPassword_WhenCalledWithSamePassword_ShouldReplaceSaltAndHashAndKeepVerificationValid()
        {
            var sut = new User("tester", "tester@example.com", "S3cureP@ss!", "Tester");
            var originalSalt = sut.Salt;
            var originalHash = sut.PasswordHash;

            sut.SetPassword("S3cureP@ss!");

            Assert.False(string.IsNullOrWhiteSpace(sut.Salt));
            Assert.False(string.IsNullOrWhiteSpace(sut.PasswordHash));
            Assert.NotEqual(originalSalt, sut.Salt);
            Assert.NotEqual(originalHash, sut.PasswordHash);
            Assert.True(sut.CheckPassword("S3cureP@ss!"));
        }

        [Theory]
        [InlineData(UserRole.User, false)]
        [InlineData(UserRole.Admin, true)]
        public void CanModify_ForContentOfOtherUser_OnlyAllowsAdmins(UserRole role, bool expected)
        {
            // Guids are generated by the database, so set them explicitly for unsaved entities.
            var sut = new User("tester", "tester@example.com", "S3cureP@ss!", "Tester") { Role = role, Guid = Guid.NewGuid() };
            var owner = new User("owner", "owner@example.com", "S3cureP@ss!", "Owner") { Guid = Guid.NewGuid() };

            Assert.Equal(expected, sut.CanModify(owner));
        }

        [Fact]
        public void CanModify_ForOwnContent_ReturnsTrue()
        {
            var sut = new User("tester", "tester@example.com", "S3cureP@ss!", "Tester");

            Assert.True(sut.CanModify(sut));
        }
    }
}
